node {
   def mvnHome
   def image
   stage('Preparation') {
      git 'https://github.com/Tomas1612/TrabajoIngSoft'
      mvnHome = tool 'M3'
   }
   stage('Build') {
      withEnv(["MVN_HOME=$mvnHome"]) {
        dir('server/'){sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore clean package'}
		dir('server/'){image = docker.build("macrosizen/server")}
      }
   }
   stage('Sonar Cloud') {
	 withEnv(["MVN_HOME=$mvnHome"]) {
	    sh 'cd server && "$MVN_HOME/bin/mvn" verify sonar:sonar -Dsonar.projectKey=Tomas1612_TrabajoIngSoft -Dsonar.organization=tomas1612 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=dfbf8525eac709bdf61b797c0378b18ce4a8cd42 -Dmaven.test.failure.ignore=true'
	}

   }
   stage('Push Image') {
     docker.withRegistry('', 'dockerhub') {
	   image.push()
	 }
   }
   stage('Push Image Heroku') {
      withCredentials([usernamePassword(credentialsId: 'herokuCredentials', passwordVariable: 'password',
      usernameVariable: 'user')]){
     sh 'docker login --username=_ --password=${password} registry.heroku.com'
     sh 'docker tag macrosizen/server registry.heroku.com/aqueous-river-20462/web'
     sh 'docker push registry.heroku.com/aqueous-river-20462/web'
     sh 'heroku container:release web -a aqueous-river-20462'
      }
     }

   stage('Integration test'){
      sh 'cd server/src/test/payrol-test && node node_modules/.bin/codeceptjs run --steps --reporter mocha-multi'
   }
   
   stage('Results') {
      archiveArtifacts 'server/target/*.jar'
      archiveArtifacts 'server/src/test/payroll-test/output/result.xml'
      junit '*/target/surefire-reports/TEST-*.xml'
      archiveArtifacts 'server/target/surefire-reports/*.xml'
   }
}