node {
   def mvnHome
   def image
   stage('Preparation') {
      git 'https://github.com/Tomas1612/TrabajoIngSoft'
      mvnHome = tool 'M3'
   }
   stage('Build') {
      withEnv(["MVN_HOME=$mvnHome"]) {
        dir('server/'){sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore clean package'}
		dir('server/'){image = docker.build("macrosizen/server")}
      }
   }
   /*
   stage('Sonar Cloud') {
	 withEnv(["MVN_HOME=$mvnHome"]) {
	    sh 'cd server && "$MVN_HOME/bin/mvn" verify sonar:sonar -Dsonar.projectKey=Tomas1612_TrabajoIngSoft -Dsonar.organization=tomas1612 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=dfbf8525eac709bdf61b797c0378b18ce4a8cd42 -Dmaven.test.failure.ignore=true'
	}

   }
   stage('Push Image') {
     docker.withRegistry('', 'dockerhub') {
	   image.push()
	 }
   }*/
   stage('Push Image Heroku') {
      withCredentials([usernamePassword(credentialsId: 'herokuCredentials', passwordVariable: 'password',
      usernameVariable: 'user')]){
     sh 'docker login --username=_ --password=f204baa3-42ac-4e1b-bb72-2c506e9058df registry.heroku.com'
     sh 'docker tag macrosizen/server registry.heroku.com/obscure-badlands-70475/web'
     sh 'docker push registry.heroku.com/obscure-badlands-70475/web'
     sh 'heroku container:release web -a obscure-badlands-70475'
      }
     }

   stage('Results') {
      archiveArtifacts 'server/target/*.jar'
      junit '*/target/surefire-reports/TEST-*.xml'
   }
}