node {
   def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/Tomas1612/TrabajoIngSoft'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configuredkbib
      // **       in the global configuration.           
      mvnHome = tool 'M3'
   }
   stage('Build') {
      // Run the maven build
      withEnv(["MVN_HOME=$mvnHome"]) {
             dir('server/') {
             if (isUnix()) {
                sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore clean package'
             } else {
                bat(/"%MVN_HOME%\bin\mvn" -Dmaven.test.failure.ignore clean package/)
             }
         }
      }
   }
   stage('Results') {
      //junit '**/target/surefire-reports/TEST-*.xml'
      archiveArtifacts '**/target/*.jar'
   }
   stage 'SonarCloud'
    // Split https://github.com/organization/repository/pull/123
    def urlcomponents = env.CHANGE_URL.split("/")
    def org = urlcomponents[3]
    def repo = urlcomponents[4]
    withSonarQubeEnv('SonarCloud') {
    mvn verify sonar:sonar \
   -Dsonar.projectKey=Tomas1612_TrabajoIngSoft \
   -Dsonar.organization=tomas1612 \
   -Dsonar.host.url=https://sonarcloud.io \
   -Dsonar.login=2af12740582afb38ce4d7dca0427271de37abc95 
}